import { IReview } from './types';

export const reviews: IReview[] = [
  {
    id: 1,
    content: 'Cảnh quan nơi đây trên cả mong đợi, khung cảnh thiên nhiên hùng vĩ và không khí trong lành.',
    name_user_review: 'Ngô Châu Bảo Khanh',
    fullName: 'Ngô Châu Bảo Khanh',
    time_review: '1/10/2024 13:45',
    start: 5,
    avatar: 'https://banahills.sunworld.vn/wp-content/uploads/2024/04/DJI_0004-1-scaled.jpg',
  },
  {
    id: 2,
    content: 'Mình thích cái cách người dân nơi đây tiếp đón mình thật sự, họ tử tế và vui vẻ lắm.',
    name_user_review: 'Trần Đình Quý',
    fullName: 'Trần Đình Quý',
    time_review: '23/9/2024 8:32',
    start: 5,
    avatar: 'https://vietsensetravel.com/view/at_tong-hop-cac-tour-du-lich-da-nang-hap-dan_58e99afe10c4c5479a1c5d1ba68b9b97.jpg',
  },
  {
    id: 3,
    content: 'Mình thắc mắc tại sao nơi đây vẫn chưa được mệnh danh là thiên đường ẩm thực nhỉ, dường như sơn hào hải vị trên thế gian đều có thể được tìm thấy ở đây ấy',
    name_user_review: 'Ngô Ngọc Hoàng Vương',
    fullName: 'Ngô Ngọc Hoàng Vương',
    time_review: '1/7/2024  9:28',
    start: 5,
    avatar: 'https://res.klook.com/image/upload/q_85/c_fill,w_750/v1705907713/ikh5vbdiprroxn5fadnd.jpg',
  },
  {
    id: 4,
    content: 'chắc chắn mình sẽ quay lại đây nhiều lần nữa, chất lượng thật sự rất tương xứng với giá tiền bỏ ra',
    name_user_review: 'Ngô Bảo Khang',
    fullName: 'Ngô Bảo Khang',
    time_review: '5/7/2024 16:02',
    start: 5,
    avatar: 'https://duonggiahotel.vn/wp-content/uploads/2023/11/dia-diem-du-lich-da-nang-avt.jpg',
  },
  {
    id: 5,
    content: 'Tôi rất hứng thú với nền văn hóa nơi đây, đa dạng và mang đậm bản sắc người Việt',
    name_user_review: 'Châu Thị Diễm',
    fullName: 'Châu Thị Diễm',
    time_review: ' 10/2/2024 20:08',
    start: 5,
    avatar: 'https://statics.vinpearl.com/le-hoi-da-nang-3_1632922702.jpg',
  },
  {
    id: 6,
    content: 'Quả thật là một thành phố hiện đại và đáng sống, cơ sở hạ tầng rất thuận lợi cho di chuyển, tham quan và du lịch',
    name_user_review: 'Nguyễn Ngọc Mai Khanh',
    fullName: 'Nguyễn Ngọc Mai Khanh',
    time_review: ' 6/9/2024 7:30',
    start: 5,
    avatar: 'https://thuexemaydanang.com.vn/wp-content/uploads/2021/04/maxresdefault-0946.jpg',
  },
  {
    id: 7,
    content: 'Thật không hổ danh là thành phố du lịch, tôi dường như có rất nhiều lựa chọn nơi ở, hầu như tất cả đều rất mới mẻ và có dịch vụ tốt',
    name_user_review: 'Ngô Ngọc Hoàng Vương',
    time_review: '9/10/2024 23:08',
    start: 5,
    avatar: 'https://booking.muongthanh.com/upload_images/images/M%C6%B0%E1%BB%9Dng%20Thanh%20Luxury%20%C4%90%C3%A0%20N%E1%BA%B5ng.jpg',
  },
  {
    id: 8,
    content: 'Tôi thật bất ngờ với các hoạt động du lịch tại đây, có rất nhiều hoạt động cho du khách như pháo hoa hay nhạc hội, tất cả đều rất tuyệt vời',
    name_user_review: 'Ngô Châu Bảo Khanh',
    time_review: ' 15/8/2024 17:02',
    start: 5,
    avatar: 'https://static.vinwonders.com/production/le-hoi-o-da-nang-1.jpg',
  },
  {
    id: 9,
    content: 'Amazing!!, I love it !! ',
    name_user_review: 'John Peterson',
    time_review: '30/9/2024 11:44',
    start: 5,
    avatar: 'https://vnn-imgs-a1.vgcloud.vn/image1.ictnews.vn/_Files/2020/03/17/trend-avatar-1.jpg',
  },
  {
    id: 10,
    content: 'The atmosphere is insane!!',
    name_user_review: 'David',
    time_review: '23/9/2024 5:45',
    start: 5,
    avatar: 'https://vnn-imgs-a1.vgcloud.vn/image1.ictnews.vn/_Files/2020/03/20/trend-avatar-12.jpg',
  },
  {
    id: 11,
    content: 'quite expensive but worthwhile :P',
    name_user_review: 'William',
    time_review: '13/5/2024 16:30',
    start: 5,
    avatar: 'https://vnn-imgs-a1.vgcloud.vn/image1.ictnews.vn/_Files/2020/02/25/trend-avatar-6.jpg',
  },
  {
    id: 12,
    content: 'Mình yêu cái đẹp và cả những dịch vụ tuyệt vời ở đây',
    name_user_review: 'Việt Hà',
    time_review: '21/4/2024 14:43',
    start: 5,
    avatar: 'https://vnn-imgs-a1.vgcloud.vn/image1.ictnews.vn/_Files/2020/03/21/trend-avatar-7.jpg',
  },
  {
    id: 13,
    content: 'Dịch vụ ở đây không quá đắt nhưng thật sự vẫn rất khó tiếp cận với đại đa số khách hàng',
    name_user_review: 'Quang Khánh',
    time_review: '19/1/2024 17:56',
    start: 2,
    avatar: 'https://vnn-imgs-a1.vgcloud.vn/image1.ictnews.vn/_Files/2020/03/21/trend-avatar-13.jpeg.jpg',
  },
  {
    id: 14,
    content: '저는 이 도시의 멋진 여행 경험에 정말 매료되었습니다. 특히 모두의 친절함에 감동받았습니다.',
    name_user_review: '전정국',
    time_review: '1/9/2024. 19:42',
    start: 5,
    avatar: 'https://vnn-imgs-a1.vgcloud.vn/image1.ictnews.vn/_Files/2020/03/04/trend-avatar-9.jpg',
  },
  {
    id: 15,
    content: 'Rất đáng để thử, chắc chắn sẽ quay lại lần sau!!',
    name_user_review: 'Trần Tín',
    time_review: '24/4/2024 13:02',
    start: 5,
    avatar: 'https://vnn-imgs-a1.vgcloud.vn/image1.ictnews.vn/_Files/2020/03/07/trend-avatar-10.jpg',
  },
  {
    id: 16,
    content: 'ベトナムでの本当に興味深い経験',
    name_user_review: 'Tomoka',
    time_review: '15/12/2023 17:38',
    start: 5,
    avatar: 'https://cellphones.com.vn/sforum/wp-content/uploads/2023/10/avatar-trang-51.jpg',
  },
  {
    id: 17,
    content: 'Nhất định phải mang theo máy ảnh để ghi lại những khoảnh khắc tuyệt vời ở đây nhé !!',
    name_user_review: 'Tấn Minh',
    time_review: '22/4/2024 19:53',
    start: 5,
    avatar: 'https://cellphones.com.vn/sforum/wp-content/uploads/2023/10/avatar-trang-11.jpg',
  },
  {
    id: 18,
    content: 'Cần thêm một vài điểm đột phá để mang lại nhiều trải nghiệm thú vị hơn!!',
    name_user_review: 'Công Mẫn',
    time_review: '3/11/2023 22:05',
    start: 3,
    avatar: 'https://tintuc.dienthoaigiakho.vn/wp-content/uploads/2024/01/avatar-nam-nu-trang-12.jpg',
  },
  {
    id: 19,
    content: 'Suitable for those who like to travel !!',
    name_user_review: 'Liz',
    time_review: '28/9/2023 17:09',
    start: 5,
    avatar: 'https://tintuc.dienthoaigiakho.vn/wp-content/uploads/2024/01/avatar-trang-nu-11.jpg',
  },
  {
    id: 20,
    content: 'Nhất định phải thử những món ăn tuyệt vời ở đâyyy',
    name_user_review: 'Quốc Huy',
    time_review: '15/2/2024 13:12',
    start: 5,
    avatar: 'https://tintuc.dienthoaigiakho.vn/wp-content/uploads/2024/01/avatar-trang-nu-13.jpg',
  },
  {
    id: 21,
    content: 'I love VietNamm <3',
    name_user_review: 'Thomas',
    time_review: '14/5/2024 11: 57',
    start: 5,
    avatar: 'https://tintuc.dienthoaigiakho.vn/wp-content/uploads/2024/01/avatar-nam-nu-trang-6.jpg',
  },
  {
    id: 22,
    content: '이곳은 매우 아름답고 명승지가 많고 사람들이 친절하며 가격이 저렴합니다.',
    name_user_review: '김남준',
    time_review: '12/9/2023 21:08',
    start: 5,
    avatar: 'https://tintuc.dienthoaigiakho.vn/wp-content/uploads/2024/01/avatar-facebook-trang-8-1.jpg',
  },
  {
    id: 23,
    content: 'Mình đã có những trải nghiệm tuyệt vời cùng gia đình mình !',
    name_user_review: 'Xuân Hiệp',
    time_review: '6/9/2024 12:44',
    start: 5,
    avatar: 'https://tintuc.dienthoaigiakho.vn/wp-content/uploads/2024/01/avatar-facebook-trang-7-2.jpg',
  },
  {
    id: 24,
    content: 'Mọi thứ thật tuyệt vời, chỉ là vẫn còn những lỗi nhỏ để có thể trở nên hoàn hảo',
    name_user_review: 'Hoàng Kiên',
    time_review: '13/4/2024',
    start: 4,
    avatar: 'https://tintuc.dienthoaigiakho.vn/wp-content/uploads/2024/01/59d24ea49dc6ecd890c9b00f85c4aecb.jpg',
  },
  {
    id: 25,
    content: '나는 확실히 여기에 여러 번 돌아올 것입니다. 품질은 가격에 비례합니다.',
    name_user_review: '박지민',
    time_review: '31/10/2023 6:58',
    start: 5,
    avatar: 'https://tintuc.dienthoaigiakho.vn/wp-content/uploads/2024/01/avatar-trang-nu-6.jpg',
  },
  {
    id: 26,
    content: 'Nó có một sự đặc trưng chẳng thể tìm thấy ở đâu khácc O_O',
    name_user_review: ' Gia Khang',
    time_review: ' 20/12/2023 12:04',
    start: 5,
    avatar: 'https://tintuc.dienthoaigiakho.vn/wp-content/uploads/2024/01/avatar-trang-nu-8.jpg',
  },
  {
    id: 27,
    content: 'It\'s really familiar to foreigners like us.Anyway, appreciate!',
    name_user_review: 'Thomas',
    time_review: '13/8/2023 18:48',
    start: 5,
    avatar: 'https://tintuc.dienthoaigiakho.vn/wp-content/uploads/2024/01/avatar-trang-nu-2.jpg',
  },
  {
    id: 28,
    content: 'जिस तरह से यहां के लोग मेरा स्वागत करते हैं वह मुझे पसंद है, वे बहुत दयालु और खुशमिजाज हैं।',
    name_user_review: 'Ajay',
    time_review: '24/3/2024 12:49',
    start: 5,
    avatar: 'https://tintuc.dienthoaigiakho.vn/wp-content/uploads/2024/01/avatar-trang-nu-1.jpg',
  },
  {
    id: 29,
    content: '真正的现代化宜居城市，基础设施十分便利，出行、观光、出行十分便利。',
    name_user_review: '黄 贺 江',
    time_review: '6/7/2024 7:56 ',
    start: 5,
    avatar: 'https://tintuc.dienthoaigiakho.vn/wp-content/uploads/2024/01/avatar-facebook-trang-2-2.jpg',
  },
]
